---
- name: stop rolldice app
  hosts: localhost
  gather_facts: false
  tasks:
    - name: stop any running Flask processes
      ansible.builtin.shell: |
        pkill -f "python rolldice.py" || true
        pkill -f "opentelemetry-instrument" || true
        pkill -f "kubectl port-forward.*4317" || true
      ignore_errors: true

- name: remove k8s-infra helm chart
  hosts: localhost
  gather_facts: false
  tasks:
    - name: uninstall k8s-infra helm chart
      kubernetes.core.helm:
        name: k8s-infra
        release_namespace: default
        state: absent
        wait: true
        wait_timeout: 300
      ignore_errors: true

    - name: remove signoz helm repository
      kubernetes.core.helm_repository:
        name: signoz
        state: absent
      ignore_errors: true

- name: stop signoz docker compose
  hosts: localhost
  gather_facts: false
  tasks:
    - name: stop signoz containers
      community.docker.docker_compose_v2:
        project_src: signoz
        state: absent
      ignore_errors: true

- import_playbook: k8s/down.yml
