---
- import_playbook: k8s/up.yml

- name: start signoz via docker compose
  hosts: localhost
  gather_facts: false
  tasks:
    - name: apply signoz patch
      ansible.builtin.shell: |
        cd signoz && patch -p1 < ../signoz/patch.diff
      ignore_errors: true

    - name: start signoz docker compose
      community.docker.docker_compose_v2:
        project_src: signoz
        files:
          - docker-compose.yml
        state: present
        wait: false
      register: signoz_result
      ignore_errors: true

    - name: wait for core signoz services to be healthy
      ansible.builtin.shell: |
        timeout 180 bash -c '
        while true; do
          if docker ps --filter "name=signoz" --filter "health=healthy" | grep -q "healthy"; then
            echo "SigNoz core service is healthy"
            break
          fi
          echo "Waiting for SigNoz to be healthy..."
          sleep 5
        done'
      register: health_check

- name: install k8s-infra helm chart
  hosts: localhost
  gather_facts: false
  tasks:
    - name: add signoz helm repository
      kubernetes.core.helm_repository:
        name: signoz
        repo_url: https://charts.signoz.io
        state: present

    - name: update helm repositories
      kubernetes.core.helm:
        name: signoz
        chart_ref: signoz
        update_repo_cache: true
        state: absent
        wait: false
      ignore_errors: true

    - name: install k8s-infra helm chart
      kubernetes.core.helm:
        name: k8s-infra
        chart_ref: signoz/k8s-infra
        release_namespace: default
        create_namespace: true
        values_files:
          - override-values.yaml
        state: present
        wait: true
        wait_timeout: 600s

- import_playbook: rolldice.up.yml
